###
POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "username" : "oddessey",
    "password" : "sanj123",
    "email" : "oddessey@123"
}
###

###
GET http://localhost:5000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoib2RkZXNzZXkiLCJpYXQiOjE2ODg5NzI2NTksImV4cCI6MTY4ODk3MjY4OX0.qaLFiDakX8GVAJLF62bPezdD4_aesRRYiJB75Yo0FbM
###

GET http://localhost:5000/auth/refresh